"""Add student_project boolean

Revision ID: 51f1ca64e659
Revises: 2798f5af52d8
Create Date: 2020-01-30 12:56:25.405435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f1ca64e659'
down_revision = '2798f5af52d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('student_project', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'student_project')
    # ### end Alembic commands ###
