"""Add image column to project

Revision ID: b4beb9e54871
Revises: 51f1ca64e659
Create Date: 2020-01-31 00:07:21.986684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4beb9e54871'
down_revision = '51f1ca64e659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image')
    # ### end Alembic commands ###
