"""add project ordering

Revision ID: cac482b65c62
Revises: b4beb9e54871
Create Date: 2020-05-13 15:08:50.787929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac482b65c62'
down_revision = 'b4beb9e54871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('ordering', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'ordering')
    # ### end Alembic commands ###
